name: studio_accordo_app_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.19.1
  cupertino_icons: ^2.0.0
  dio: ^5.11.1
  envied: ^1.3.10
  flutter_mobx: ^2.4.0
  flutter_svg: ^2.3.0
  flutter_screenutil: ^5.9.3
  get_it: ^9.3.0
  go_router: ^18.0.2
  google_fonts: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^3.0.0
  json_annotation: ^4.12.0
  mobx: ^2.7.0
  moment_dart: ^5.3.4
  package_info_plus: ^10.2.2
  pretty_dio_logger: ^1.4.0
  record: ^7.1.1
  shimmer: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.16.1
  envied_generator: ^1.3.10
  json_serializable: ^6.14.1
  injectable_generator: ^3.1.3
  mobx_codegen: ^2.8.0
  flutter_launcher_icons: ^0.14.4



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/logo.png"
  image_path_ios_dark_transparent: "assets/logo/logo_transparent.png"
  image_path_ios_tinted_grayscale: "assets/logo/logo_transparent.png"
  desaturate_tinted_to_grayscale_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#1f1a15"
  adaptive_icon_foreground: "assets/logo/logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
